version: '3.9'

services:
  db:
    container_name: girka_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test:
        [ 
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - girka-network
networks:
  girka-network:
    driver: bridge
